- name: Install some basic apt package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - wget
    - git
    - vim
    - htop
    - tmux
    - python-dev
    - libpq-dev

- name: vim settings
  copy:
    src: vimrc
    dest: /root/.vimrc
